# Generated by Django 4.2.6 on 2023-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="_id",
        ),
        migrations.AddField(
            model_name="genre",
            name="tmbd_id",
            field=models.IntegerField(blank=True, default=None, unique=True),
        ),
    ]
