# Generated by Django 4.2.6 on 2023-10-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_tmbd_id_genre_tmdb_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="duration",
        ),
    ]
