# Generated by Django 4.2.6 on 2023-10-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_movie_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="studio",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.studio"
            ),
        ),
    ]
