# Generated by Django 4.2.6 on 2023-10-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_movie_studio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="country",
        ),
    ]
