# Generated by Django 4.2.6 on 2023-10-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_movie_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviecredit",
            name="character",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="moviecredit",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="moviecredit",
            name="profile_path",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="moviecredit",
            name="role",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
