# Generated by Django 4.2.6 on 2023-10-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_moviecredit_character_moviecredit_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviecredit",
            name="personTMDBId",
            field=models.IntegerField(blank=True, default=None, unique=True),
        ),
    ]
