# Generated by Django 4.2.6 on 2023-10-19 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_moviecredit_persontmdbid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moviecredit",
            name="role",
        ),
        migrations.AddField(
            model_name="moviecredit",
            name="job",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.job"
            ),
        ),
    ]
