# Generated by Django 4.2.6 on 2023-10-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_moviecredit_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecredit",
            name="person",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.person"
            ),
        ),
    ]
