# Generated by Django 4.2.6 on 2023-10-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_moviecredit_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecredit",
            name="profile_path",
            field=models.URLField(blank=True, default=None),
        ),
    ]
