# Generated by Django 4.2.6 on 2023-10-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_moviecredit_profile_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="country",
        ),
        migrations.RemoveField(
            model_name="person",
            name="imageURL",
        ),
        migrations.AddField(
            model_name="person",
            name="known_for_department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="profile_path",
            field=models.URLField(blank=True),
        ),
    ]
