# Generated by Django 4.2.6 on 2023-10-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_person_country_remove_person_imageurl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="tmdb_id",
            field=models.IntegerField(blank=True, default=None, unique=True),
        ),
    ]
