# Generated by Django 4.2.6 on 2023-10-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_person_tmdb_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
