# Generated by Django 4.2.6 on 2023-10-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_person_birthdate_alter_person_place_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecredit",
            name="personTMDBId",
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
