# Generated by Django 4.2.6 on 2023-10-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_moviecredit_persontmdbid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="place_of_birth",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
