# Generated by Django 4.2.6 on 2023-10-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_person_place_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="biography",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
